# Generated by Django 5.2.8 on 2025-11-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journey",
            name="crew",
            field=models.ManyToManyField(to="railway.crew"),
        ),
    ]
