# Generated by Django 5.2.8 on 2025-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0003_journey_crew"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude"), name="unique_station"
            ),
        ),
    ]
