# Generated by Django 5.2.8 on 2025-11-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0004_station_unique_station"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="station",
            name="unique_station",
        ),
        migrations.AlterUniqueTogether(
            name="station",
            unique_together={("latitude", "longitude")},
        ),
    ]
