# Generated by Django 5.2.8 on 2025-11-28 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0005_remove_station_unique_station_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("cargo", "seat", "journey")},
        ),
    ]
