# Generated by Django 5.2.8 on 2025-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0006_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
