# Generated by Django 5.2.8 on 2025-11-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0008_alter_route_distance_alter_train_cargo_num_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="crew",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="journey",
            options={"ordering": ["departure_time"]},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ["distance"]},
        ),
        migrations.AlterModelOptions(
            name="station",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="train",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="traintype",
            options={"ordering": ["name"]},
        ),
    ]
