# Generated by Django 5.2.8 on 2025-11-28 23:54

import railway.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0009_alter_crew_options_alter_journey_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crew",
            name="image",
            field=models.ImageField(
                null=True, upload_to=railway.models.crew_image_path
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="image",
            field=models.ImageField(
                null=True, upload_to=railway.models.station_image_path
            ),
        ),
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(
                null=True, upload_to=railway.models.train_image_path
            ),
        ),
    ]
