# Generated by Django 5.2.8 on 2025-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("railway", "0010_crew_image_station_image_train_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
